import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalBackground from "@/components/GlobalBackground";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { checkUser } from "@/lib/checkUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SENSAI",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await checkUser(); // sync user here (server side)

  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <GlobalBackground />
          <div className="relative z-10 min-h-screen">{children}</div>
          <footer className="bg-muted/50 py-5">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p>Made with 💗 by Dipal</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
